const TYPE_HOTEL = 1
const GROUP_TYPE_PARAM = 1 //参数设置
const GROUP_TYPE_MAKECARD = 2//制卡
const GROUP_TYPE_CHECKOUT = 4//离店

export { TYPE_HOTEL, GROUP_TYPE_PARAM, GROUP_TYPE_MAKECARD, GROUP_TYPE_CHECKOUT }